### ISSUE TITLE
Static icon.

### ISSUE THREAD

**Issue by mikaelsundin** [Styort/LogViewer#1]
Great project. 

One thing i wish is to have a static icon instead of the animated one. 
For me it draws attention away from other windows.

Perhaps a setting in the settings page?

**Comment by Styort** [comment]
> Great project.
> 
> One thing i wish is to have a static icon instead of the animated one. For me it draws attention away from other windows.
> 
> Perhaps a setting in the settings page?

Hi. Thanks!
What icons exactly are you talking about? Do you mean the animation of the icon in the taskbar when receiving logs via upd? This can be disabled in the settings by unchecking the 'Show UPD progress on taskbar icon'.

**Comment by mikaelsundin** [comment]
Perfect, i missed the settings to disable the taskbar animation.
